Implementación de lo visto en la clase 3
kevmpr/react-learning-camp pull request #3
Opened 2024-06-13 02:20 UTC by kevmpr

- Creación de un index.html, una carpeta llamada css y un styles.css
- Creación de etiquetas semánticas como header, nav, main y footer
- Uso de flex
- Uso de box-sizing: border-box
- intento de uso de la metodología de nomenclatura BEM

2024-06-14 20:13 UTC, nicmalegre requested changes
Muy bien @kevmpr. Destaco que la PR tiene una descripción muy detallada y está muy prolijo el naming de los diferentes estilos en el css. 

Lo marco como 'request changes' porque veo que estás eliminando todo lo de `class1/` y `class2/ `. Por las dudas eso no fue por error?

2024-06-16 22:01 UTC, kevmpr commented
> Muy bien @kevmpr. Destaco que la PR tiene una descripción muy detallada y está muy prolijo el naming de los diferentes estilos en el css.
> 
> Lo marco como 'request changes' porque veo que estás eliminando todo lo de `class1/` y `class2/ `. Por las dudas eso no fue por error?

2024-06-19 20:48 UTC, nicmalegre commented
> Buenas Profe!! Borré las carpetas class1 y class2 en la rama de class3 para que solo este la carpeta de class3. Si mergeo class3 a main, las carpetas class1 y class2 que ya están en la rama principal se borran? O solo se suma la carpeta class3? Si se borran, como debería hacer para la rama class3? Debería tener en class3 las carpetas class1, class2 y class3? Espero su respuesta!!

Exactamente, todos los cambios que hagas dentro de la `branch3` van a pasar a `main` cuando hagas el merge de la PR. Por lo tanto, si borras un archivo en `class3` y después haces el merge a `main`, ese archivo también se va a borrar en la branch `main`. 
Siempre una PR tiene un cambio o un conjunto de cambios que son "mergeados" de una branch a otra. Esos cambios siempre podes revisarlos dentro de la sección de [Files changed](https://github.com/kevmpr/react-learning-camp/pull/3/files). 

En este caso, si borras las carpetas `class1` y `class2` en la branch `class3` y después mandas esos cambios a `main` también se van a borrar en `main` al momento que se junten los cambios. Por lo tanto, en la branch `class3` lo único que deberías hacer es agregar la nueva carpeta `class3` con todos sus archivos correspondientes y sin borrar las carpetas `class1` y `class2`. Lo que ya estaba desde antes no se modifica, seguirán estando como ya estaban. En esta PR solo incluimos cambios relacionados con clase 3. Espero que se entienda, cualquier cosa avisame y lo repasamos 💪🏼

2024-06-19 23:39 UTC, kevmpr commented
> > Buenas Profe!! Borré las carpetas class1 y class2 en la rama de class3 para que solo este la carpeta de class3. Si mergeo class3 a main, las carpetas class1 y class2 que ya están en la rama principal se borran? O solo se suma la carpeta class3? Si se borran, como debería hacer para la rama class3? Debería tener en class3 las carpetas class1, class2 y class3? Espero su respuesta!!
> 
> Exactamente, todos los cambios que hagas dentro de la `branch3` van a pasar a `main` cuando hagas el merge de la PR. Por lo tanto, si borras un archivo en `class3` y después haces el merge a `main`, ese archivo también se va a borrar en la branch `main`. Siempre una PR tiene un cambio o un conjunto de cambios que son "mergeados" de una branch a otra. Esos cambios siempre podes revisarlos dentro de la sección de [Files changed](https://github.com/kevmpr/react-learning-camp/pull/3/files).
> 
> En este caso, si borras las carpetas `class1` y `class2` en la branch `class3` y después mandas esos cambios a `main` también se van a borrar en `main` al momento que se junten los cambios. Por lo tanto, en la branch `class3` lo único que deberías hacer es agregar la nueva carpeta `class3` con todos sus archivos correspondientes y sin borrar las carpetas `class1` y `class2`. Lo que ya estaba desde antes no se modifica, seguirán estando como ya estaban. En esta PR solo incluimos cambios relacionados con clase 3. Espero que se entienda, cualquier cosa avisame y lo repasamos 💪🏼
> 
> Una vez que hayas solucionado eso, podes volver a pedirme review así la acepto 👍🏼

Ok profe, ahora lo hago

2024-06-22 00:31 UTC, kevmpr commented
Buenas profe!! Ya agregué las carpetas de las clases anteriores. Estaría todo listo?

2024-06-28 02:42 UTC, merged