Implementación de lo visto en la clase 4
kevmpr/react-learning-camp pull request #4
Opened 2024-06-13 03:20 UTC by kevmpr

- Creación de index.html, calculadora.html, cuentaRegresiva,html, carpeta js,  calculadora.js y cuentaRegresiva.js
- Cree un calculadora que puede sumar, restar, multiplicar y dividir usando un switch
- Cree un cuenta regresiva usando un for.

2024-06-14 20:16 UTC, nicmalegre commented on class4/js/calculadora.js
> +        Sumar();
```suggestion
        sumar();
```
Es más normal encontrar los nombres de funciones con la primer letra en minúscula: conocido también como [camelcase](https://developer.mozilla.org/en-US/docs/Glossary/Camel_case)

2024-06-14 20:16 UTC, nicmalegre commented on class4/js/calculadora.js
> +        Restar()
```suggestion
        restar()
```

2024-06-14 20:16 UTC, nicmalegre commented on class4/js/calculadora.js
> +        Multiplicar();
```suggestion
        multiplicar();
```

2024-06-14 20:16 UTC, nicmalegre commented on class4/js/calculadora.js
> +        Dividir();
```suggestion
        dividir();
```

2024-06-14 20:19 UTC, nicmalegre commented on class4/js/calculadora.js
> +    let num2 = parseInt(prompt('Escriba el segundo numero a sumar'))
Es necesario utilizar `let` acá? Si es un valor que no va a ser modificado se puede usar `const`

2024-06-14 20:19 UTC, nicmalegre commented on class4/js/calculadora.js
> +    let resultado = num1 + num2;
Lo mismo acá 
```suggestion
    const resultado = num1 + num2;
```

2024-06-14 20:33 UTC, nicmalegre commented on class4/js/calculadora.js
> +    let num2 = parseInt(prompt('Escriba el segundo numero a restar'))
Es muy normal en un proyecto tener un mismo código que necesitamos en varios lugares. En general, se intenta evitar repetir y, en lugar de eso, abstraer todo ese código en una función y poder reutilizarla. Eso nos permite poder actualizar más fácilmente en un solo lugar entre otras ventajas.
Veo que venis avanzando muy bien así que te quería proponer si te animas a abstraer este código:
```
 const num1 = parseInt(prompt('Escriba el primer numero a restar'));
 const num2 = parseInt(prompt('Escriba el segundo numero a restar'))
```
 a una función y lo reutilizas? 
 Lo único que cambia entre uno y otro es la operación: 'a sumar', 'a restar', 'a multiplicar', 'a dividir'. Así que podría ser una función que recibe por params la operación y devuelve `num1` y `num2`. 
 Para utilizarla sería así: 
` const [num1, num2] = obtenerNumeros('sumar')`

Que te parece? Sino lo podemos dejar para una futura PR 👍🏼

2024-06-14 20:36 UTC, nicmalegre requested changes
La clase 4 la veo muy bien, ya estaría aprobada 👏🏼 Me queda la duda de por qué se está eliminando `class1/` y `class2/` ?

2024-06-16 22:08 UTC, kevmpr commented on class4/js/calculadora.js
> +    let num2 = parseInt(prompt('Escriba el segundo numero a restar'))
Buenas Profe!! Gracias por las sugerencias y correcciones. Voy a hacerlo ahora!!

2024-06-16 22:39 UTC, kevmpr commented
Buenas profe!! Intenté hacer lo que me dijo usted y creo que me salió!! Estoy muy contento, quedo bastante limpio el código. También implemente un While para que pueda hacer cuantas operaciones quiera sin recargar la pagina, y una opción para salir del bucle. Espero su respuesta!! 
PD: Sobre la eliminación de las carpetas class1 y class2, las borré porque queria que la rama solo tuviera la carpeta class4, esta bien asi? O deberia tener las 3 carpetas anteriores y la actual?

2024-06-19 20:51 UTC, nicmalegre commented on class4/js/calculadora.js
> +}
Excelente 👏🏼

2024-06-19 20:54 UTC, nicmalegre commented
> Buenas profe!! Intenté hacer lo que me dijo usted y creo que me salió!! Estoy muy contento, quedo bastante limpio el código. También implemente un While para que pueda hacer cuantas operaciones quiera sin recargar la pagina, y una opción para salir del bucle. Espero su respuesta!! PD: Sobre la eliminación de las carpetas class1 y class2, las borré porque queria que la rama solo tuviera la carpeta class4, esta bien asi? O deberia tener las 3 carpetas anteriores y la actual?

Muy buen trabajo 💪🏼 Lo veo mucho más prolijo y ahora podes reutilizar la función y, en caso que necesites, podes actualizar solamente una función en lugar de hacerlo en 4 lugares diferentes. A seguir así! 
Con respecto a la eliminación de carpetas, [acá hay una respuesta más detallada](https://github.com/kevmpr/react-learning-camp/pull/3#issuecomment-2179438962) pero en concreto si, deberías mantener las 3 carpetas anteriores y en esta PR solamente agregar la nueva `class4/ `

2024-06-19 23:46 UTC, kevmpr commented
> > Buenas profe!! Intenté hacer lo que me dijo usted y creo que me salió!! Estoy muy contento, quedo bastante limpio el código. También implemente un While para que pueda hacer cuantas operaciones quiera sin recargar la pagina, y una opción para salir del bucle. Espero su respuesta!! PD: Sobre la eliminación de las carpetas class1 y class2, las borré porque queria que la rama solo tuviera la carpeta class4, esta bien asi? O deberia tener las 3 carpetas anteriores y la actual?
> 
> Muy buen trabajo 💪🏼 Lo veo mucho más prolijo y ahora podes reutilizar la función y, en caso que necesites, podes actualizar solamente una función en lugar de hacerlo en 4 lugares diferentes. A seguir así! Con respecto a la eliminación de carpetas, [acá hay una respuesta más detallada](https://github.com/kevmpr/react-learning-camp/pull/3#issuecomment-2179438962) pero en concreto si, deberías mantener las 3 carpetas anteriores y en esta PR solamente agregar la nueva `class4/ `. Una vez que quede eso corregido ya la puedo aceptar. El resto está todo perfecto

Buenas profe!! Muchas gracias!! Ahora lo corrijo

2024-06-22 00:32 UTC, kevmpr commented
Buenas profe, ya agregué las carpetas de las clases 1, 2 y 3. Estaría todo listo para mergear?

2024-06-28 02:42 UTC, merged